language: rust
rust: nightly
cache: cargo

before_script:
- rustup component add rust-src
- cd ..
- (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
- (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
- cargo install-update -a
- cd $TRAVIS_BUILD_DIR

script:
- xargo check
