language: rust
rust: nightly
cache: cargo

install:
- rustup component add rust-src
- cd ..
- (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
- (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
- cargo install-update -a
- cd $TRAVIS_BUILD_DIR

before_script:
- xargo check
- rustc --test ./src/test.rs

script:
- RUST_BACKTRACE=1 ./test

